### ISSUE TITLE
Resource-specific healthcheck extensions

### ISSUE THREAD

**Issue by Kralizek** [aspirant-project/aspirant#6]
Is it ok to make a PR to port here the resource-specific healthcheck extensions from [this repository](https://github.com/davidfowl/WaitForDependenciesAspire) by @davidfowl ?

If so, do you have any preference for a package naming scheme? 

Suggestions could be:
- `Aspirant.Hosting.<Resource>` to create a single extension package for each resource type
- `Aspirant.Hosting.Healthchecks.<Resource>` to keep the package scope narrow

**Comment by DamianEdwards** [comment]
The first is what I had in mind, so one can easily swap out a reference for `Aspire.Hosting.Redis` with `Aspirant.Hosting.Redis`, and so on.
